# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: GDFI-Dev-Team/gdfi-website
  base_url: https://sveltia-cms-auth.raki-rarufu-dev.workers.dev
media_folder: /public/media
public_folder: /media

media_libraries:
  # handoff later
  cloudflare_r2: 
    access_key_id: 9c671155033e705d9900c1857e7b81cc
    bucket: sveltia-media
    account_id: ffa0678267bca3257f3209173022c26f 
    public_url: https://pub-a32043e692ef4f1f91a01e5573fd355d.r2.dev
    prefix: gdfi-website-uploads/
  all:
    transformations:
      raster_image:
        format: webp
      svg:
        optimize: true

collections:
  - name: test-pages
    label: Test Pages
    folder: content/test-pages
    media_folder: /public/test-pages
    fields: 
      - { label: Title, name: title, widget: string }
      - label: Featured Image
        name: thumbnail
        widget: image
        media_libraries:
          default: false
        hint: This image will be used as the thumbnail image.
      - { label: Date, name: date, widget: datetime, type: date }
      - { label: Body, name: body, widget: richtext }
